name: "Build the AppImage"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |            
          *.AppImage
    - run: nix build .#gossip-minimal-appimage
    - run: mv ./result ./Gossip-${{ github.ref_name }}-minimal-x86_64.AppImage
